apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc0001
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: pv0001
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce